[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "comp0034-activities"
version = "2025.01"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "uvicorn",
    "sqlmodel",
    "pytest",
    "pandas",
    "alembic",
    "openpyxl",
    "streamlit",
    "plotly",
    "requests",
    "pyjwt",
    "pydantic-settings",
    "pwdlib[argon2,bcrypt]"
]
