"""Pydantic schemas for API requests and responses

Generated by CoPilot using the prompt: Generate Pydantic Base, Create, Read and Update schemas for all classes in models.py. Base defines the core fields, others inherit from that.

Included for those using SQLAlchemy
"""
from typing import Optional
from pydantic import BaseModel, ConfigDict, field_validator


# ============================================================================
# Games Schemas
# ============================================================================

class GamesBase(BaseModel):
    """Base schema for Games with core fields"""
    event_type: str
    year: int
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    countries: Optional[int] = None
    events: Optional[int] = None
    sports: Optional[int] = None
    participants_m: Optional[int] = None
    participants_f: Optional[int] = None
    participants: Optional[int] = None
    highlights: Optional[str] = None
    url: Optional[str] = None

    @field_validator("event_type")
    @classmethod
    def validate_event_type(cls, value: str) -> str:
        allowed = ["winter", "summer"]
        value = value.lower()
        if value not in allowed:
            raise ValueError(f"{value} is not in {allowed}")
        return value

    @field_validator("year")
    @classmethod
    def validate_year(cls, value: int) -> int:
        value = int(value)
        if value < 1960 or value > 9999:
            raise ValueError(f"{value} must be between 1960 and 9999")
        return value


class GamesCreate(GamesBase):
    """Schema for creating a new Games record"""
    pass


class GamesRead(GamesBase):
    """Schema for reading a Games record"""
    id: int
    hosts: list["HostRead"] = []
    disabilities: list["DisabilityRead"] = []
    teams: list["TeamRead"] = []

    model_config = ConfigDict(from_attributes=True)


class GamesUpdate(BaseModel):
    """Schema for updating a Games record - all fields optional"""
    event_type: Optional[str] = None
    year: Optional[int] = None
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    countries: Optional[int] = None
    events: Optional[int] = None
    sports: Optional[int] = None
    participants_m: Optional[int] = None
    participants_f: Optional[int] = None
    participants: Optional[int] = None
    highlights: Optional[str] = None
    url: Optional[str] = None

    @field_validator("event_type")
    @classmethod
    def validate_event_type(cls, value: Optional[str]) -> Optional[str]:
        if value is not None:
            allowed = ["winter", "summer"]
            value = value.lower()
            if value not in allowed:
                raise ValueError(f"{value} is not in {allowed}")
        return value

    @field_validator("year")
    @classmethod
    def validate_year(cls, value: Optional[int]) -> Optional[int]:
        if value is not None:
            value = int(value)
            if value < 1960 or value > 9999:
                raise ValueError(f"{value} must be between 1960 and 9999")
        return value


# ============================================================================
# Team Schemas
# ============================================================================

class TeamBase(BaseModel):
    """Base schema for Team with core fields"""
    code: str
    name: str
    region: Optional[str] = None
    member_type: str
    notes: Optional[str] = None
    country_id: Optional[str] = None

    @field_validator("member_type")
    @classmethod
    def validate_member_type(cls, value: str) -> str:
        allowed = ["country", "team", "dissolved", "construct"]
        if value not in allowed:
            raise ValueError(f"{value} is not in {allowed}")
        return value

    @field_validator("region")
    @classmethod
    def validate_region(cls, value: Optional[str]) -> Optional[str]:
        allowed = ["Asia", "Europe", "Africa", "America", "Oceania"]
        if value is not None and value not in allowed:
            raise ValueError(f"{value} is not in {allowed}")
        return value


class TeamCreate(TeamBase):
    """Schema for creating a new Team record"""
    pass


class TeamRead(TeamBase):
    """Schema for reading a Team record"""

    model_config = ConfigDict(from_attributes=True)


class TeamUpdate(BaseModel):
    """Schema for updating a Team record - all fields optional"""
    name: Optional[str] = None
    region: Optional[str] = None
    member_type: Optional[str] = None
    notes: Optional[str] = None
    country_id: Optional[str] = None

    @field_validator("member_type")
    @classmethod
    def validate_member_type(cls, value: Optional[str]) -> Optional[str]:
        if value is not None:
            allowed = ["country", "team", "dissolved", "construct"]
            if value not in allowed:
                raise ValueError(f"{value} is not in {allowed}")
        return value

    @field_validator("region")
    @classmethod
    def validate_region(cls, value: Optional[str]) -> Optional[str]:
        allowed = ["Asia", "Europe", "Africa", "America", "Oceania"]
        if value is not None and value not in allowed:
            raise ValueError(f"{value} is not in {allowed}")
        return value


# ============================================================================
# Disability Schemas
# ============================================================================

class DisabilityBase(BaseModel):
    """Base schema for Disability with core fields"""
    description: str


class DisabilityCreate(DisabilityBase):
    """Schema for creating a new Disability record"""
    pass


class DisabilityRead(DisabilityBase):
    """Schema for reading a Disability record"""
    id: int
    model_config = ConfigDict(from_attributes=True)


class DisabilityUpdate(BaseModel):
    """Schema for updating a Disability record - all fields optional"""
    description: Optional[str] = None


# ============================================================================
# Host Schemas
# ============================================================================

class HostBase(BaseModel):
    """Base schema for Host with core fields"""
    place_name: str
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    country_id: Optional[int] = None


class HostCreate(HostBase):
    """Schema for creating a new Host record"""
    pass


class HostRead(HostBase):
    """Schema for reading a Host record"""
    id: int

    model_config = ConfigDict(from_attributes=True)


class HostUpdate(BaseModel):
    """Schema for updating a Host record - all fields optional"""
    place_name: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    country_id: Optional[int] = None


# ============================================================================
# Country Schemas
# ============================================================================

class CountryBase(BaseModel):
    """Base schema for Country with core fields"""
    country_name: str


class CountryCreate(CountryBase):
    """Schema for creating a new Country record"""
    pass


class CountryRead(CountryBase):
    """Schema for reading a Country record"""
    id: int

    model_config = ConfigDict(from_attributes=True)


class CountryUpdate(BaseModel):
    """Schema for updating a Country record - all fields optional"""
    country_name: Optional[str] = None


# ============================================================================
# Question Schemas
# ============================================================================

class QuestionBase(BaseModel):
    """Base schema for Question with core fields"""
    question_text: str


class QuestionCreate(QuestionBase):
    """Schema for creating a new Question record"""
    pass


class QuestionRead(QuestionBase):
    """Schema for reading a Question record"""
    id: int
    responses: list["ResponseRead"] = []

    model_config = ConfigDict(from_attributes=True)


class QuestionUpdate(BaseModel):
    """Schema for updating a Question record - all fields optional"""
    question_text: Optional[str] = None


# ============================================================================
# Response Schemas
# ============================================================================

class ResponseBase(BaseModel):
    """Base schema for Response with core fields"""
    question_id: Optional[int] = None
    response_text: str
    is_correct: bool


class ResponseCreate(ResponseBase):
    """Schema for creating a new Response record"""
    pass


class ResponseRead(ResponseBase):
    """Schema for reading a Response record"""
    id: int

    model_config = ConfigDict(from_attributes=True)


class ResponseUpdate(BaseModel):
    """Schema for updating a Response record - all fields optional"""
    question_id: Optional[int] = None
    response_text: Optional[str] = None
    is_correct: Optional[bool] = None


# ============================================================================
# Link Table Schemas (for many-to-many relationships)
# ============================================================================

class GamesHostBase(BaseModel):
    """Base schema for GamesHost link table"""
    games_id: int
    host_id: int


class GamesHostCreate(GamesHostBase):
    """Schema for creating a new GamesHost link"""
    pass


class GamesHostRead(GamesHostBase):
    """Schema for reading a GamesHost link"""
    id: int

    model_config = ConfigDict(from_attributes=True)


class GamesDisabilityBase(BaseModel):
    """Base schema for GamesDisability link table"""
    games_id: int
    disability_id: int


class GamesDisabilityCreate(GamesDisabilityBase):
    """Schema for creating a new GamesDisability link"""
    pass


class GamesDisabilityRead(GamesDisabilityBase):
    """Schema for reading a GamesDisability link"""
    id: int

    model_config = ConfigDict(from_attributes=True)


class GamesTeamBase(BaseModel):
    """Base schema for GamesTeam link table"""
    games_id: int
    team_id: str


class GamesTeamCreate(GamesTeamBase):
    """Schema for creating a new GamesTeam link"""
    pass


class GamesTeamRead(GamesTeamBase):
    """Schema for reading a GamesTeam link"""
    id: int

    model_config = ConfigDict(from_attributes=True)


# Update forward references for nested models
GamesRead.model_rebuild()
QuestionRead.model_rebuild()

